battlecat/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

from hordak import views as hordak_views


hordak_urls = [
    url(r'^transactions/create/$', hordak_views.TransactionCreateView.as_view(), name='transactions_create'),
    url(r'^transactions/currency/$', hordak_views.CurrencyTradeView.as_view(), name='currency_trade'),
    url(r'^transactions/reconcile/$', hordak_views.TransactionsReconcileView.as_view(), name='transactions_reconcile'),
    url(r'^$', hordak_views.AccountListView.as_view(), name='accounts_list'),
    url(r'^accounts/create/$', hordak_views.AccountCreateView.as_view(), name='accounts_create'),
    url(r'^accounts/update/(?P<uuid>.+)/$', hordak_views.AccountUpdateView.as_view(), name='accounts_update'),
    url(r'^accounts/(?P<uuid>.+)/$', hordak_views.AccountTransactionsView.as_view(), name='accounts_transactions'),

    url(r'^import/$', hordak_views.CreateImportView.as_view(), name='import_create'),
    url(r'^import/(?P<uuid>.*)/setup/$', hordak_views.SetupImportView.as_view(), name='import_setup'),
    url(r'^import/(?P<uuid>.*)/dry-run/$', hordak_views.DryRunImportView.as_view(), name='import_dry_run'),
    url(r'^import/(?P<uuid>.*)/run/$', hordak_views.ExecuteImportView.as_view(), name='import_execute'),
]

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include(hordak_urls, namespace='hordak', app_name='hordak')),
]

if settings.ENABLE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

example_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('battlecat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

battlecat/accounts/models.py
from django.db import models

# Create your models here.

battlecat/transactions/models.py
from django.db import models

# Create your models here.

battlecat/accounts/views.py
from django.shortcuts import render

# Create your views here.

battlecat/transactions/views.py
from django.shortcuts import render

# Create your views here.

battlecat/accounts/templates/hordak/accounts/account_create.html
{% extends 'hordak/accounts/account_create.html' %}
{% load bootstrap3 %}

{% block page_name %}Create account{% endblock %}
{% block page_description %}Create a new account{% endblock %}

{% block content %}
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}

        <p>
            <input type="submit" class="btn btn-primary btn-lg pull-right" value="Create account">
            <a href="{% url 'hordak:accounts_list' %}" class="btn btn-lg pull-right">Cancel</a>
        </p>
    </form>
{% endblock %}

battlecat/accounts/templates/hordak/accounts/account_list.html
{% extends 'hordak/accounts/account_list.html' %}

battlecat/accounts/templates/hordak/accounts/account_transactions.html
{% extends 'hordak/accounts/account_transactions.html' %}

battlecat/accounts/templates/hordak/accounts/account_update.html
{% extends 'hordak/accounts/account_update.html' %}
{% load bootstrap3 %}

{% block page_name %}Edit account{% endblock %}
{% block page_description %}Create a new account{% endblock %}

{% block content %}
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}

        {% bootstrap_form form layout='horizontal' %}

        <div class="form-group">
            <label class="col-sm-3 control-label">Type</label>
            <div class="col-sm-9">
                <div class="form-control-static">{{ account.get__type_display }}</div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">Currencies</label>
            <div class="col-sm-9">
                <div class="form-control-static">{{ account.currencies|join:', ' }}</div>
            </div>
        </div>

        <p>
            <input type="submit" class="btn btn-primary btn-lg pull-right" value="Save changes">
            <a href="{% url 'hordak:accounts_list' %}" class="btn btn-lg pull-right">Cancel</a>
        </p>
    </form>

{% endblock %}

battlecat/core/templates/adminlte/lib/_main_header.html
{% extends 'adminlte/lib/_main_header.html' %}

{#{% block logo_href %}{% url 'dashboard:dashboard' %}{% endblock %}#}

{% block logo_text %}<b>Battle</b>Cat{% endblock %}

{% block logo_text_small %}<b>B</b>C{% endblock %}

{#{% block logout_url %}/set-me-later{% endblock %}#}

battlecat/core/templates/adminlte/lib/_main_sidebar.html
{% extends 'adminlte/lib/_main_sidebar.html' %}
{% load battlecat battlecat %}

{% block nav_links %}

    <li><a href="{% url 'hordak:accounts_list' %}"><i class="fa fa-tachometer"></i> <span>Accounts</span></a></li>

    <li><a href="{% url 'hordak:transactions_create' %}"><i class="fa fa-arrow-circle-right"></i> <span>Create Transaction</span></a></li>
    <li>
        <a href="{% url 'hordak:transactions_reconcile' %}">
            <i class="fa fa-arrows-h"></i>
            <span>Reconcile statements</span>
            <span class="pull-right-container">
                {% total_unreconciled as t %}
                <small class="label pull-right {% if t > 0 %}bg-yellow{% else %}bg-green{% endif %}">{{ t }}</small>
            </span>
        </a>
    </li>
    <li><a href="{% url 'hordak:currency_trade' %}"><i class="fa fa-arrow-circle-right"></i> <span>Exchange Currency</span></a></li>

    {% comment %}
    <li><a href="{% url 'costs:recurring' %}"><i class="fa fa-clock-o"></i> <span>Recurring Costs</span></a></li>
    <li><a href="{% url 'costs:one_off' %}"><i class="fa fa-money"></i> <span>One-off Costs</span></a></li>
    <li><a href="{% url 'housemates:list' %}"><i class="fa fa-group"></i> <span>Housemates</span></a></li>

    <li><a href="{% url 'transactions:import_create' %}"><i class="fa fa-upload"></i> <span>Import Statement</span></a></li>
    {% endcomment %}
{% endblock nav_links %}

battlecat/core/templates/battlecat/core/base.html
{% extends 'adminlte/base.html' %}
{% load static %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "core/css/common.css" %}">
{% endblock %}

battlecat/core/templates/battlecat/core/includes/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}. Total results: {{ page_obj.paginator.count }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

battlecat/core/templates/battlecat/core/test.html
{% extends 'battlecat/core/base.html' %}

{% block content %}
    Hello?
{% endblock %}

{% block page_name %}
Test page
{% endblock %}

{% block page_description %}
Page description
{% endblock %}

battlecat/core/templates/core/test.html
{% extends 'core/base.html' %}

{% block content %}
    Hello?
{% endblock %}

{% block page_name %}
Test page
{% endblock %}

{% block page_description %}
Page description
{% endblock %}

battlecat/core/templates/hordak/base.html
{% extends 'battlecat/core/base.html' %}

battlecat/core/templates/hordak/partials/form.html
{% load bootstrap3 %}
{% bootstrap_form form layout='horizontal' %}

battlecat/core/templates/hordak/statement_import/import_create.html
{% extends 'hordak/statement_import/import_create.html' %}
{% load bootstrap3 %}

{% block content %}
    <p>
        Select a CSV file to import. You will then be able to review and reconcile each
        entry, thereby entering it into your accounting system.
    </p>

    <form action="{% url 'hordak:import_create' %}" method="post" enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        {% block form_content %}
            {% bootstrap_field form.bank_account layout='horizontal' %}
            {% bootstrap_field form.file layout='horizontal' %}
            {% bootstrap_field form.has_headings layout='horizontal' %}
            <input type="submit" class="btn btn-primary btn-lg pull-right" value="Continue...">
        {% endblock %}
    </form>
{% endblock %}

battlecat/core/templates/hordak/statement_import/import_dry_run.html
{% extends 'hordak/statement_import/import_dry_run.html' %}

battlecat/core/templates/hordak/statement_import/import_execute.html
{% extends 'hordak/statement_import/import_execute.html' %}

battlecat/core/templates/hordak/statement_import/import_setup.html
{% extends 'hordak/statement_import/import_setup.html' %}

battlecat/transactions/templates/hordak/transactions/create_transaction.html
{% extends 'hordak/transactions/transaction_create.html' %}

battlecat/transactions/templates/hordak/transactions/currency_trade.html
{% extends 'hordak/transactions/currency_trade.html' %}
{% load bootstrap3 %}

{% block form %}
<form action="{% url 'hordak:currency_trade' %}" method="post" class="form-horizontal">
    {% csrf_token %}
    {% block form_content %}

        {% bootstrap_field form.source_account layout='horizontal' %}
        {% bootstrap_field form.source_amount layout='horizontal' form_group_class='form-group money' %}
        {% bootstrap_field form.trading_account layout='horizontal' %}
        {% bootstrap_field form.destination_account layout='horizontal' %}
        {% bootstrap_field form.destination_amount layout='horizontal' form_group_class='form-group money' %}
        {% bootstrap_field form.description layout='horizontal' %}

        <p>
            <input type="submit" value="Create Trade" class="btn btn-primary btn-lg pull-right">
            <a href="{% url 'hordak:accounts_list' %}" class="btn btn-lg pull-right">Cancel</a>
        </p>
    {% endblock %}
</form>
{% endblock %}

battlecat/transactions/templates/hordak/transactions/reconcile.html
{% extends 'hordak/transactions/reconcile.html' %}
{% load bootstrap3 %}

{% block reconcile_form_content %}
    {% bootstrap_field transaction_form.description show_label=False %}
    {{ leg_formset.management_form }}
    <table class="table table-striped">
        {% for form in leg_formset %}
            <tr>
                <td>{% bootstrap_field form.amount show_label=False show_help=False form_group_class='form-group money' %}</td>
                <td>{% bootstrap_field form.description show_label=False show_help=False %}</td>
                <td>{% bootstrap_field form.account show_label=False show_help=False %}</td>
            </tr>
        {% endfor %}
    </table>

    <input type="submit" value="Reconcile" class="btn btn-success pull-right">
{% endblock reconcile_form_content %}

battlecat/transactions/templates/hordak/transactions/transaction_create.html
{% extends 'hordak/transactions/transaction_create.html' %}
{% load bootstrap3 %}

{% block content %}
    <form action="{% url 'hordak:transactions_create' %}" method="post" class="form-horizontal">
        {% csrf_token %}
        {% block form_content %}
            {% bootstrap_field form.amount layout='horizontal' form_group_class='form-group money' %}
            {% bootstrap_field form.from_account layout='horizontal' %}
            {% bootstrap_field form.to_account layout='horizontal' %}
            {% bootstrap_field form.description layout='horizontal' %}
            <p>
                <input type="submit" value="Create Transaction" class="btn btn-primary btn-lg pull-right">
                <a href="{% url 'hordak:accounts_list' %}" class="btn btn-lg pull-right">Cancel</a>
            </p>
        {% endblock %}
    </form>
{% endblock %}